export const ELECTION_ACTIONS = {
  CREATE: 'CREATE_ELECTION',
  UPDATE: 'UPDATE_ELECTION',
  ARCHIVE: 'SOFT_DELETE_ELECTION',
  RESTORE: 'RESTORE_DELETE_ELECTION',
  START: 'START_ELECTION',
  CLOSE: 'CLOSE_ELECTION',
  CANCEL: 'CANCEL_ELECTION',
} as const;
