export const POSITION_ACTIONS = {
  COMBOBOX: 'COMBOBOX_POSITIONS',
  CREATE: 'CREATE_POSITION',
  UPDATE: 'UPDATE_POSITION',
  ARCHIVE: 'SOFT_DELETE_POSITION',
  RESTORE: 'RESTORE_DELETE_POSITION',
  FIND_WITH_FILTERS: 'FIND_POSITIONS_WITH_FILTERS',
} as const;
