export const POSITION_ACTIONS = {
  DEFAULT: 'DEFAULT_ACTION',
  CREATE: 'CREATE_POSITION',
  UPDATE: 'UPDATE_POSITION',
  ARCHIVE: 'SOFT_DELETE_POSITION',
  RESTORE: 'RESTORE_DELETE_POSITION',
  FIND_WITH_FILTERS: 'FIND_POSITIONS_WITH_FILTERS',
} as const;
