export const ACTIVE_ELECTION_ACTIONS = {
  SET_ACTIVE_ELECTION: 'SET_ACTIVE_ELECTION',
  RETRIEVE_ACTIVE_ELECTION: 'RETRIEVE_ACTIVE_ELECTION',
  RESET_ACTIVE_ELECTION: 'RESET_ACTIVE_ELECTION',
};

export const ACTIVE_ELECTION_ID = 1;
