export const USER_ROLE_ACTIONS = {
  CREATE: 'CREATE_USER_ROLE',
  UPDATE: 'UPDATE_USER_ROLE',
  ARCHIVE: 'SOFT_DELETE_USER_ROLE',
  RESTORE: 'RESTORE_DELETE_USER_ROLE',
  FIND_WITH_FILTERS: 'FIND_USER_ROLES_WITH_FILTERS',
  COMBOBOX: 'COMBOBOX_USER_ROLES',
} as const;
