import React, { useEffect, useState } from "react";
import { Calendar, Monitor, Globe, ShieldAlert, User } from "lucide-react";
import { cn } from "@/lib/utils";
import { Card } from "@/components/ui/card";
import { CardContent } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";

const CSharedReportFooter = ({ className }: { className?: string }) => {
  const [systemInfo, setSystemInfo] = useState<string>("");
  const [formattedDate, setFormattedDate] = useState<string>("");
  const [formattedTime, setFormattedTime] = useState<string>("");

  useEffect(() => {
    // Get browser and OS information
    const userAgent = navigator.userAgent;
    const browserInfo = userAgent.match(
      /(chrome|safari|firefox|msie|trident|edge)\/([\d.]+)/i
    );
    const osInfo = userAgent.match(
      /(windows|mac|linux|android|ios)\s+([\w\s.]+)/i
    );

    const browser = browserInfo ? browserInfo[1] : "Unknown Browser";
    const os = osInfo ? osInfo[1] : "Unknown OS";

    setSystemInfo(`${os} / ${browser}`);

    // Format date and time
    const date = new Date();
    setFormattedDate(
      date.toLocaleDateString("en-US", {
        timeZone: "Asia/Manila",
        year: "numeric",
        month: "long",
        day: "numeric",
      })
    );

    setFormattedTime(
      date.toLocaleTimeString("en-US", {
        timeZone: "Asia/Manila",
        hour: "2-digit",
        minute: "2-digit",
        second: "2-digit",
      })
    );
  }, []);

  return (
    <Card
      className={cn(
        "mt-8 print:mt-6 border-t shadow-none rounded-none border-x-0 border-b-0",
        className
      )}
    >
      <CardContent className="text-xs text-muted-foreground pt-3 px-0 flex flex-col items-center">
        <div className="flex flex-col gap-1.5 print:break-inside-avoid items-center w-full">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-3 w-full justify-items-center justify-center">
            <div className="flex items-center justify-center text-center">
              <Calendar className="h-3.5 w-3.5 mr-1.5" />
              <div>
                <p className="font-medium">Generated</p>
                <p>
                  {formattedDate} <span className="mx-1">•</span>{" "}
                  {formattedTime}
                  <span className="ml-1.5 text-[0.7rem] opacity-75">
                    ({Intl.DateTimeFormat().resolvedOptions().timeZone})
                  </span>
                </p>
              </div>
            </div>
            <div className="flex items-center justify-center text-center">
              <Monitor className="h-3.5 w-3.5 mr-1.5" />
              <div>
                <p className="font-medium">Environment</p>
                <p>{systemInfo}</p>
              </div>
            </div>
            <div className="flex items-center justify-center text-center">
              <User className="h-3.5 w-3.5 mr-1.5" />
              <div>
                <p className="font-medium">Generated by</p>
                <p>Admin</p>
              </div>
            </div>
            <div className="flex items-center justify-center text-center">
              <Globe className="h-3.5 w-3.5 mr-1.5" />
              <div>
                <p className="font-medium">Network</p>
                <p>{window.location.hostname}</p>
              </div>
            </div>
          </div>

          <Separator className="my-1.5" />

          <div className="flex flex-col items-center gap-1.5 ">
            <div className="flex items-center gap-2">
              <ShieldAlert className="h-4 w-4 text-red-600" />
              <span className="text-red-600 font-medium text-[0.7rem] tracking-wide uppercase">
                Classification: Company Confidential
              </span>
            </div>
            <p className="text-center text-[0.7rem] opacity-75">
              AMPC HRIS V2.0
            </p>
          </div>
        </div>
      </CardContent>
    </Card>
  );
};

export default CSharedReportFooter;
