import { BadRequestException, Injectable } from '@nestjs/common';
import { Inject } from '@nestjs/common';
import { REPOSITORY_TOKENS } from '@shared/constants/tokens.constants';
import { ActiveElectionRepository } from '@domains/repositories/active-election.repository';
import { TransactionPort } from '@domain/ports/transaction-port';
import { ReportsRepository } from '@domains/repositories/reports.repository';
import { ActivityLog } from '@domain/models/activitylog.model';
import { DATABASE_CONSTANTS } from '@shared/constants/database.constants';
import { ActivityLogRepository } from '@domains/repositories/activity-log.repository';
import { ElectionRepository } from '@domains/repositories/election.repository';
import { getPHDateTime } from '@domain/utils/format-ph-time';
import { CAST_VOTE_ACTIONS } from '@domain/constants/cast-vote/cast-vote-actions.constants';

@Injectable()
export class CastVoteReportUseCase {
  constructor(
    @Inject(REPOSITORY_TOKENS.REPORTS)
    private readonly reportsRepository: ReportsRepository,
    @Inject(REPOSITORY_TOKENS.ACTIVE_ELECTION)
    private readonly activeElectionRepository: ActiveElectionRepository,
    @Inject(REPOSITORY_TOKENS.TRANSACTIONPORT)
    private readonly transactionHelper: TransactionPort,
    @Inject(REPOSITORY_TOKENS.ACTIVITYLOGS)
    private readonly activityLogRepository: ActivityLogRepository,
    @Inject(REPOSITORY_TOKENS.ELECTION)
    private readonly electionRepository: ElectionRepository,
  ) {}

  /**
   * Executes the use case for finding districts with filters.
   * @param user_name The user name.
   * @returns An object containing filtered districts and total count.
   */
  async execute(user_name: string): Promise<any> {
    return this.transactionHelper.executeTransaction(
      CAST_VOTE_ACTIONS.CAST_VOTES_REPORT,
      async (manager) => {
        const active_election =
          await this.activeElectionRepository.retrieveActiveElection(manager);
        if (!active_election) {
          throw new BadRequestException('No Active election');
        }
        const election = await this.electionRepository.findById(
          active_election.election_id,
          manager,
        );

        // Call the repository method to get filtered data
        const result: any[] =
          await this.reportsRepository.electionCastVoteReport(
            active_election.election_id,
            manager,
          );

        // Transform the result to the required format
        const grouped_result = [];
        const position_map = new Map();
        for (const row of result) {
          if (!position_map.has(row.position)) {
            position_map.set(row.position, {
              position: row.position,
              candidates: [],
            });
          }
          position_map.get(row.position).candidates.push({
            name: row.candidate,
            vote_count: Number(row.vote_count),
          });
        }
        for (const value of position_map.values()) {
          grouped_result.push(value);
        }

        // Log the archive
        const log = ActivityLog.create({
          action: CAST_VOTE_ACTIONS.CAST_VOTES_REPORT,
          entity: DATABASE_CONSTANTS.MODELNAME_CAST_VOTE,
          details: JSON.stringify({
            explanation: `Cast votes report generated by USER : ${user_name}`,
            generated_by: user_name,
            generated_at: getPHDateTime(),
          }),
          user_name: user_name,
        });
        await this.activityLogRepository.create(log, manager);

        return {
          data: grouped_result,
          election: election,
        };
      },
    );
  }
}
