

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4iLCJzdWIiOjEsInVzZXJSb2xlcyI6WyJhZG1pbiJdLCJhcHBsaWNhdGlvbkFjY2VzcyI6WyJhZG1pbiBtb2R1bGUiLCJlbGVjdGlvbiBtb2R1bGUiXSwicHJlY2luY3QiOiJkZWZhdWx0IiwiaWF0IjoxNzY1MjYwNTExLCJleHAiOjE3NjUyODkzMTF9.-T1HaAlIU6WkFXALvjD6pYfANq4snllYsgBbXHHhCJU

@baseurl=http://localhost:3090/api/v1/active-election


###
# SET ACTIVE ELECTION 
PATCH  {{baseurl}}/set-active
Content-Type: application/json
Authorization: Bearer {{token}}

{
   "electionName": "Representative Assembly 2026"
}

###
# RESET 
PATCH  {{baseurl}}/reset
Content-Type: application/json
Authorization: Bearer {{token}}



###
# GET ACTIVE ELECTION 
GET  {{baseurl}}
Content-Type: application/json
Authorization: Bearer {{token}}