

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4iLCJzdWIiOjUsInVzZXJSb2xlcyI6WyJBZG1pbiJdLCJhcHBsaWNhdGlvbkFjY2VzcyI6WyJBZG1pbiBtb2R1bGUiLCJFbGVjdGlvbiBtb2R1bGUiXSwicHJlY2luY3QiOiJEZWZhdWx0IiwiaWF0IjoxNzY1MjQ0MDM1LCJleHAiOjE3NjUyNzI4MzV9.rZ-0YV_HvrKn9jKdEXuUZie6oCMxFZUXouLeFOcQVgE
@baseurl=http://localhost:3090/api/v1/active-election


###
# SET ACTIVE ELECTION 
PATCH  {{baseurl}}/set-active
Content-Type: application/json
Authorization: Bearer {{token}}

{
   "electionName": "Representative Assembly 2026"
}

###
# RESET 
PATCH  {{baseurl}}/reset
Content-Type: application/json
Authorization: Bearer {{token}}



###
# GET ACTIVE ELECTION 
GET  {{baseurl}}
Content-Type: application/json
Authorization: Bearer {{token}}