

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4iLCJzdWIiOjMsInVzZXJSb2xlcyI6WyJBZG1pbiJdLCJhcHBsaWNhdGlvbkFjY2VzcyI6WyJBZG1pbiBtb2R1bGUiLCJFbGVjdGlvbiBtb2R1bGUiXSwicHJlY2luY3QiOiJEZWZhdWx0IiwiaWF0IjoxNzY0OTE0NDEzLCJleHAiOjE3NjQ5NDMyMTN9.5RAdKA02BBgTDF3u2KSdtn7yxG7W3tfCLqsKkPcwvlg

@baseurl=http://localhost:3090/api/v1/active-election


###
# SET ACTIVE ELECTION 
PATCH  {{baseurl}}/set-active
Content-Type: application/json
Authorization: Bearer {{token}}

{
   "electionName": "Representative Assembly 2026"
}

###
# RESET 
PATCH  {{baseurl}}/reset
Content-Type: application/json
Authorization: Bearer {{token}}



###
# GET ACTIVE ELECTION 
GET  {{baseurl}}
Content-Type: application/json
Authorization: Bearer {{token}}