
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4iLCJzdWIiOjEsInVzZXJSb2xlcyI6WyJBZG1pbiJdLCJhcHBsaWNhdGlvbkFjY2VzcyI6WyJBZG1pbiBtb2R1bGUiLCJFbGVjdGlvbiBtb2R1bGUiXSwicHJlY2luY3QiOiJEZWZhdWx0IiwiaWF0IjoxNzY1MjU1MzU1LCJleHAiOjE3NjUyODQxNTV9.VSNCGevfE4EuUfm_05RLjylWPXhGx0edam9Bk0nCWpc

@baseurl=http://localhost:3090/api/v1

# Test Create Client
POST {{baseurl}}/districts
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "desc1": "DISTRICT 1"
}

###
# UPDATE 
PATCH  {{baseurl}}/districts/4
Content-Type: application/json
Authorization: Bearer {{token}}

{
   "desc1": "District test update"
}

###
# DELETE 
DELETE  {{baseurl}}/districts/delete/4
Content-Type: application/json
Authorization: Bearer {{token}}


###
# RESTORE 
PATCH  {{baseurl}}/districts/restore/4
Content-Type: application/json
Authorization: Bearer {{token}}

###
# GET DISTRICTS 
GET  {{baseurl}}/districts?term=&page=1&limit=50
Content-Type: application/json
Authorization: Bearer {{token}}

###
# GET COMBOBOX DISTRICTS 
GET  {{baseurl}}/districts/combobox
Content-Type: application/json
Authorization: Bearer {{token}}