
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4iLCJzdWIiOjMsInVzZXJSb2xlcyI6WyJBZG1pbiJdLCJhcHBsaWNhdGlvbkFjY2VzcyI6WyJBZG1pbiBtb2R1bGUiLCJFbGVjdGlvbiBtb2R1bGUiXSwicHJlY2luY3QiOiJEZWZhdWx0IiwiaWF0IjoxNzY0OTE0NDEzLCJleHAiOjE3NjQ5NDMyMTN9.5RAdKA02BBgTDF3u2KSdtn7yxG7W3tfCLqsKkPcwvlg


@baseurl=http://localhost:3090/api/v1

# Test Create Client
POST {{baseurl}}/districts
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "desc1": "DISTRICT 3"
}

###
# UPDATE 
PATCH  {{baseurl}}/districts/4
Content-Type: application/json
Authorization: Bearer {{token}}

{
   "desc1": "District test update"
}

###
# DELETE 
DELETE  {{baseurl}}/districts/delete/4
Content-Type: application/json
Authorization: Bearer {{token}}


###
# RESTORE 
PATCH  {{baseurl}}/districts/restore/4
Content-Type: application/json
Authorization: Bearer {{token}}

###
# GET DISTRICTS 
GET  {{baseurl}}/districts?term=&page=1&limit=50
Content-Type: application/json
Authorization: Bearer {{token}}

###
# GET COMBOBOX DISTRICTS 
GET  {{baseurl}}/districts/combobox
Content-Type: application/json
Authorization: Bearer {{token}}