

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4iLCJzdWIiOjEsInVzZXJSb2xlcyI6WyJhZG1pbiJdLCJhcHBsaWNhdGlvbkFjY2VzcyI6WyJhZG1pbiBtb2R1bGUiLCJlbGVjdGlvbiBtb2R1bGUiXSwicHJlY2luY3QiOiJkZWZhdWx0IiwiaWF0IjoxNzY1MjYwNTExLCJleHAiOjE3NjUyODkzMTF9.-T1HaAlIU6WkFXALvjD6pYfANq4snllYsgBbXHHhCJU

@baseurl=http://localhost:3090/api/v1

# Test Create Client
POST {{baseurl}}/positions
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "desc1": "DISTRICT 3 BOD",
  "maxCandidates": 3,
  "termLimit": "2 years"
}

###
# UPDATE 
PATCH  {{baseurl}}/positions/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
 "desc1": "BOD DISTRICT 1",
  "maxCandidates": 2,
  "termLimit": "2 years"
}

###
# DELETE 
DELETE  {{baseurl}}/positions/delete/1
Content-Type: application/json
Authorization: Bearer {{token}}


###
# RESTORE 
PATCH  {{baseurl}}/positions/restore/1
Content-Type: application/json
Authorization: Bearer {{token}}

###
# GET POSITIONS 
GET  {{baseurl}}/positions?term=&page=1&limit=50
Content-Type: application/json
Authorization: Bearer {{token}}

###
# GET COMBOBOX POSITIONS 
GET  {{baseurl}}/positions/combobox
Content-Type: application/json
Authorization: Bearer {{token}}