

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4iLCJzdWIiOjMsInVzZXJSb2xlcyI6WyJBZG1pbiJdLCJhcHBsaWNhdGlvbkFjY2VzcyI6WyJBZG1pbiBtb2R1bGUiLCJFbGVjdGlvbiBtb2R1bGUiXSwicHJlY2luY3QiOiJEZWZhdWx0IiwiaWF0IjoxNzY0OTE0NDEzLCJleHAiOjE3NjQ5NDMyMTN9.5RAdKA02BBgTDF3u2KSdtn7yxG7W3tfCLqsKkPcwvlg



@baseurl=http://localhost:3090/api/v1

# Test Create Client
POST {{baseurl}}/positions
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "desc1": "AUDIT COMMITTEE",
  "maxCandidates": 2,
  "termLimit": "2 years"
}

###
# UPDATE 
PATCH  {{baseurl}}/positions/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
 "desc1": "BOD DISTRICT 1",
  "maxCandidates": 2,
  "termLimit": "2 years"
}

###
# DELETE 
DELETE  {{baseurl}}/positions/delete/1
Content-Type: application/json
Authorization: Bearer {{token}}


###
# RESTORE 
PATCH  {{baseurl}}/positions/restore/1
Content-Type: application/json
Authorization: Bearer {{token}}

###
# GET POSITIONS 
GET  {{baseurl}}/positions?term=&page=1&limit=50
Content-Type: application/json
Authorization: Bearer {{token}}

###
# GET COMBOBOX POSITIONS 
GET  {{baseurl}}/positions/combobox
Content-Type: application/json
Authorization: Bearer {{token}}