
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4iLCJzdWIiOjIsInVzZXJSb2xlcyI6IkFkbWluIiwiYXBwbGljYXRpb25BY2Nlc3MiOiJBZG1pbiBNb2R1bGUsIEVsZWN0aW9uIE1hbmFnZW1lbnQgTW9kdWxlIiwiaWF0IjoxNzQ3MTkxMDAxLCJleHAiOjE3NDcyMTk4MDF9.lQqjYv8PbwTPKx1zLRMQqH-Dvs9tmkcDvZYfJuX10Ss
@baseurl=http://localhost:3090/api/v1

### Update Settings
PATCH {{baseurl}}/settings
Content-Type: application/json
Authorization: Bearer {{token}}

{
     "electionName": "Representative Assembly 2025"
}

### Reset Settings
PATCH {{baseurl}}/settings/reset
Content-Type: application/json
Authorization: Bearer {{token}}


### Retrieve Settings
GET {{baseurl}}/settings
Content-Type: application/json
Authorization: Bearer {{token}}


