import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { CandidateReport } from "@/types/reports.types";
import Image from "next/image";

export type CandidatesReportPrintProps = {
  report: CandidateReport;
};

export default function CandidatesReportPrint({
  report,
}: CandidatesReportPrintProps) {
  // Flatten all candidates into a single array with position info
  const allCandidates = report
    ? report.data?.flatMap((position) =>
        position.candidates.map((candidate) => ({
          position: position.position,
          name: candidate.name,
        }))
      )
    : [];

  return (
    <div className="print-fill-page relative print:h-full">
      {/* Watermark */}
      <div
        className="pointer-events-none select-none fixed top-0 left-5 w-full h-full flex items-center justify-center z-0 print:fixed print:top-0 print:left-5 print:w-full print:h-full"
        aria-hidden="true"
        style={{
          opacity: 0.05,
          fontSize: "3rem",
          fontWeight: "bold",
          color: "#1e293b", // Tailwind slate-800
          whiteSpace: "nowrap",
          transform: "rotate(-20deg)",
          userSelect: "none",
          pointerEvents: "none",
        }}
      >
        AGDAO MULTIPURPOSE COOPERATIVE
      </div>

      {/* Logo and header */}
      <div className="mb-6 text-center print:block relative z-10">
        <Image
          src="/logo.png"
          alt="AGDAO Multipurpose Cooperative Logo"
          className="mx-auto mb-2 print:mb-2"
          style={{ maxHeight: 80, maxWidth: 80 }}
          width={80}
          height={80}
          priority
        />
        <h1 className="text-2xl font-bold text-black text-center mb-2">
          AGDAO MULTIPURPOSE COOPERATIVE
        </h1>
        <p className="text-sm text-black mb-1">
          AMPC Head Office Bldg., N. Torres & P. Urduja Sts.
        </p>
        <p className="text-sm text-black mb-1">
          Paciano Bangoy, Davao City 8000
        </p>
        <p className="text-sm text-black mb-2">Tel: (082) 285-3797</p>

        <h2 className="text-lg font-semibold text-black mt-4 mb-2">
          Official List of Candidates
        </h2>
        <p className="text-sm text-black mb-4">
          Generated on {new Date().toLocaleDateString()} at{" "}
          {new Date().toLocaleTimeString()}
        </p>
      </div>

      <div className="mb-2">
        {report.election.name && (
          <p className="text-sm">
            Election:{" "}
            <span className="uppercase underline">{report.election.name}</span>
          </p>
        )}
        {report.election.date && (
          <p className="text-sm">
            Date: {new Date(report.election.date).toLocaleDateString()}
          </p>
        )}
        {report.election.address && (
          <p className="text-sm">
            Address: <span>{report.election.address}</span>
          </p>
        )}
        {report.election.status && (
          <p className="text-sm text-black ">
            Status: <span className="uppercase">{report.election.status}</span>
          </p>
        )}
      </div>

      {allCandidates?.length > 0 ? (
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead className="w-[80px]">No.</TableHead>
              <TableHead>Position</TableHead>
              <TableHead>Candidate Name</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {allCandidates.map((candidate, idx) => (
              <TableRow key={idx}>
                <TableCell>{idx + 1}.</TableCell>
                <TableCell>{candidate.position}</TableCell>
                <TableCell>{candidate.name}</TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      ) : (
        <div className="flex flex-col items-center justify-center py-12">
          <p className="text-muted-foreground">No candidates data available</p>
        </div>
      )}

      <div className="h-full pt-6 border-t text-sm text-center text-muted-foreground print:block">
        <p>
          This report is generated by the AGDAO Multipurpose Cooperative
          Election System.
        </p>
        <p>
          © {new Date().getFullYear()} AGDAO Multipurpose Cooperative. All
          rights reserved.
        </p>
      </div>

      <style jsx global>{`
        @media print {
          html,
          body,
          .print-fill-page {
            margin: 0 !important;
            padding: 0 !important;
            box-sizing: border-box;
            background: white !important;
            overflow: visible !important;
            -webkit-overflow-scrolling: auto !important;
          }
          ::-webkit-scrollbar {
            display: none !important;
          }
        }
      `}</style>
    </div>
  );
}
