export const DELEGATE_ACTIONS = {
  CREATE: 'CREATE_DELEGATE',
  UPDATE: 'UPDATE_DELEGATE',
  ARCHIVE: 'SOFT_DELETE_DELEGATE',
  RESTORE: 'RESTORE_DELETE_DELEGATE',
  UPLOAD_DELEGATES: 'UPLOAD_DELEGATES',
  FIND_WITH_PAGINATION: 'FIND_DELEGATES_WITH_PAGINATION',
  FIND_BY_CONTROL_NUMBER: 'FIND_DELEGATE_BY_CONTROL_NUMBER',
} as const;
