export const DISTRICT_ACTIONS = {
  CREATE: 'CREATE_DISTRICT',
  UPDATE: 'UPDATE_DISTRICT',
  ARCHIVE: 'SOFT_DELETE_DISTRICT',
  RESTORE: 'RESTORE_DELETE_DISTRICT',
  FIND_WITH_FILTERS: 'FIND_DISTRICTS_WITH_FILTERS',
  COMBOBOX: 'COMBOBOX_DISTRICTS',
} as const;
