export const USER_ACTIONS = {
  CREATE: 'CREATE_USER_ROLE',
  UPDATE: 'UPDATE_USER',
  ARCHIVE: 'SOFT_DELETE_USER',
  RESTORE: 'RESTORE_DELETE_USER',
  FIND_WITH_PAGINATION: 'FIND_USERS_WITH_PAGINATION',
} as const;
