export const LOG_ACTION_CONSTANTS = {
  // delegate

  // application access
  CREATE_APPLICATIONACCESS: 'CREATE_APPLICATIONACCESS',
  UPDATE_APPLICATIONACCESS: 'UPDATE_APPLICATIONACCESS',
  SOFT_DELETE_APPLICATIONACCESS: 'SOFT_DELETE_APPLICATIONACCESS',
  RESTORE_DELETE_APPLICATIONACCESS: 'RESTORE_DELETE_APPLICATIONACCESS',
  // user role
  CREATE_USERROLE: 'CREATE_USERROLE',
  UPDATE_USERROLE: 'UPDATE_USERROLE',
  SOFT_DELETE_USERROLE: 'SOFT_DELETE_USERROLE',
  RESTORE_DELETE_USERROLE: 'RESTORE_DELETE_USERROLE',
  // user
  CREATE_USER: 'CREATE_USER',
  UPDATE_USER: 'UPDATE_USER',
  SOFT_DELETE_USER: 'SOFT_DELETE_USER',
  RESTORE_DELETE_USER: 'RESTORE_DELETE_USER',

  UPDATE_SETTING: 'UPDATE_SETTING',
  RETRIEVE_SETTING: 'RETRIEVE_SETTING',
  RESETELECTION_SETTING: 'RESETELECTION_SETTING',
  GENERATE_ATTENDANCE_PER_BRANCH_REPORT:
    'GENERATE_ATTENDANCE_PER_BRANCH_REPORT',
  GENERATE_ATTENDANCE_LIST_PER_USER_REPORT:
    'GENERATE_ATTENDANCE_LIST_PER_USER_REPORT',
  // cast vote
  CAST_VOTE: 'CAST_VOTE',
  // upload file
  UPLOAD_FILE_PROCESSING: 'UPLOAD_FILE_PROCESSING',
  UPLOAD_FILE_FINISHED: 'UPLOAD_FILE_FINISHED',
  // reports
  GENERATE_CAST_VOTE_REPORT: 'GENERATE_CAST_VOTE_REPORT',
  GENERATE_CANDIDATES_REPORT: 'GENERATE_CANDIDATES_REPORT',
};
