export const LOG_ACTION_CONSTANTS = {
  // delegate

  GENERATE_ATTENDANCE_PER_BRANCH_REPORT:
    'GENERATE_ATTENDANCE_PER_BRANCH_REPORT',
  GENERATE_ATTENDANCE_LIST_PER_USER_REPORT:
    'GENERATE_ATTENDANCE_LIST_PER_USER_REPORT',

  // upload file
  UPLOAD_FILE_PROCESSING: 'UPLOAD_FILE_PROCESSING',
  UPLOAD_FILE_FINISHED: 'UPLOAD_FILE_FINISHED',
  // reports
  GENERATE_CAST_VOTE_REPORT: 'GENERATE_CAST_VOTE_REPORT',
  GENERATE_CANDIDATES_REPORT: 'GENERATE_CANDIDATES_REPORT',
};
