export const LOG_ACTION_CONSTANTS = {
  // district
  CREATE_DISTRICT: 'CREATE_DISTRICT',
  UPDATE_DISTRICT: 'UPDATE_DISTRICT',
  SOFT_DELETE_DISTRICT: 'SOFT_DELETE_DISTRICT',
  RESTORE_DELETE_DISTRICT: 'RESTORE_DELETE_DISTRICT',
  RETRIEVE_DISTRICTS_BY_ELECTION_ID: 'RETRIEVE_DISTRICTS_BY_ELECTION_ID',
  RETRIEVE_DISTRICTS_COMBOBOX: 'RETRIEVE_DISTRICTS_COMBOBOX',

  // candidate
  CREATE_CANDIDATE: 'CREATE_CANDIDATE',
  UPDATE_CANDIDATE: 'UPDATE_CANDIDATE',
  SOFT_DELETE_CANDIDATE: 'SOFT_DELETE_CANDIDATE',
  RESTORE_DELETE_CANDIDATE: 'RESTORE_DELETE_CANDIDATE',
  RETRIEVE_CANDIDATES_BY_ACTIVE_ELECTION:
    'RETRIEVE_CANDIDATES_BY_ACTIVE_ELECTION',
  RETRIEVE_CANDIDATES_COMBOBOX: 'RETRIEVE_CANDIDATES_COMBOBOX',
  RETRIEVE_CAST_VOTE_CANDIDATES: 'RETRIEVE_CAST_VOTE_CANDIDATES',
  // election
  START_ELECTION: 'START_ELECTION',
  CLOSE_ELECTION: 'CLOSE_ELECTION',
  CANCEL_ELECTION: 'CANCEL_ELECTION',
  CREATE_ELECTION: 'CREATE_ELECTION',
  UPDATE_ELECTION: 'UPDATE_ELECTION',
  SETACTIVE_ELECTION: 'UPDATE_SETACTIVE',
  RESETACTIVE_ELECTION: 'UPDATE_RESETACTIVE',
  SOFT_DELETE_ELECTION: 'SOFT_DELETE_ELECTION',
  RESTORE_DELETE_ELECTION: 'RESTORE_DELETE_ELECTION',
  // delegate

  CREATE_DELEGATE: 'CREATE_DELEGATE',
  UPDATE_DELEGATE: 'UPDATE_DELEGATE',
  SOFT_DELETE_DELEGATE: 'SOFT_DELETE_DELEGATE',
  RESTORE_DELETE_DELEGATE: 'RESTORE_DELETE_DELEGATE',
  RETRIEVE_DELEGATES_BY_ACTIVE_ELECTION:
    'RETRIEVE_DELEGATES_BY_ACTIVE_ELECTION',
  // application access
  CREATE_APPLICATIONACCESS: 'CREATE_APPLICATIONACCESS',
  UPDATE_APPLICATIONACCESS: 'UPDATE_APPLICATIONACCESS',
  SOFT_DELETE_APPLICATIONACCESS: 'SOFT_DELETE_APPLICATIONACCESS',
  RESTORE_DELETE_APPLICATIONACCESS: 'RESTORE_DELETE_APPLICATIONACCESS',
  // user role
  CREATE_USERROLE: 'CREATE_USERROLE',
  UPDATE_USERROLE: 'UPDATE_USERROLE',
  SOFT_DELETE_USERROLE: 'SOFT_DELETE_USERROLE',
  RESTORE_DELETE_USERROLE: 'RESTORE_DELETE_USERROLE',
  // user
  CREATE_USER: 'CREATE_USER',
  UPDATE_USER: 'UPDATE_USER',
  SOFT_DELETE_USER: 'SOFT_DELETE_USER',
  RESTORE_DELETE_USER: 'RESTORE_DELETE_USER',

  UPDATE_SETTING: 'UPDATE_SETTING',
  RETRIEVE_SETTING: 'RETRIEVE_SETTING',
  RESETELECTION_SETTING: 'RESETELECTION_SETTING',
  GENERATE_ATTENDANCE_PER_BRANCH_REPORT:
    'GENERATE_ATTENDANCE_PER_BRANCH_REPORT',
  GENERATE_ATTENDANCE_LIST_PER_USER_REPORT:
    'GENERATE_ATTENDANCE_LIST_PER_USER_REPORT',
  // cast vote
  CAST_VOTE: 'CAST_VOTE',
  // upload file
  UPLOAD_FILE_PROCESSING: 'UPLOAD_FILE_PROCESSING',
  UPLOAD_FILE_FINISHED: 'UPLOAD_FILE_FINISHED',
  // reports
  GENERATE_CAST_VOTE_REPORT: 'GENERATE_CAST_VOTE_REPORT',
  GENERATE_CANDIDATES_REPORT: 'GENERATE_CANDIDATES_REPORT',
};
