export const CANDIDATE_ACTIONS = {
  CREATE: 'CREATE_CANDIDATE',
  UPDATE: 'UPDATE_CANDIDATE',
  ARCHIVE: 'SOFT_DELETE_CANDIDATE',
  RESTORE: 'RESTORE_DELETE_CANDIDATE',
  FIND_WITH_PAGINATION: 'FIND_CANDIDATES_WITH_PAGINATION',
  GET_ELECTION_CANDIDATES: 'GET_ELECTION_CANDIDATES',
} as const;
