export const APPLICATION_ACCESS_ACTIONS = {
  CREATE: 'CREATE_APPLICATION_ACCESS',
  UPDATE: 'UPDATE_APPLICATION_ACCESS',
  ARCHIVE: 'SOFT_DELETE_APPLICATION_ACCESS',
  RESTORE: 'RESTORE_DELETE_APPLICATION_ACCESS',
  FIND_WITH_FILTERS: 'FIND_APPLICATION_ACCESSES_WITH_FILTERS',
  COMBOBOX: 'COMBOBOX_APPLICATION_ACCESSES',
} as const;
